robot:
  root_link: elfin_base_link
  tip_link: elfin_end_link

  control_point_names:

    - elfin_link3
    - elfin_link4
    - elfin_link5
    - elfin_link6

    - elfin_link2_a
    - elfin_link2_b
    - elfin_link3_a
    - elfin_link4_a

    - elfin_link4_b
    - elfin_link4_c
  control_point_radiuses:
    - 0.08
    - 0.085
    - 0.085
    - 0.09
    
    - 0.06
    - 0.06
    - 0.07
    - 0.06

    - 0.06
    - 0.05
solver:
  spacing: 0.002
  clamping:
    norm:
      - 4.0
      - 0.05
      - 2.0
      - 0.2
    iter:
      - 100
      - 50
      - 200
      - 100
  merge_attempt_interval: 500
  maxiter: 1001

obstacles:
  x:
    - 0.22
    - 0.25
    - 0.25

  y:
    - 0
    - -0.15
    - 0.15

  z:
    - 0.6
    - 0.55
    - 0.55

  r:
    - 0.05
    - 0.06
    - 0.06

    